version: "2"

volumes:
    store_lake:
        external: true
    store_mart:
        external: true
    aquila_logs:
        external: true

services:

    db:
        container_name: postgreslake
        build:
            context: "../"
            dockerfile: docker/postgresDockerfile
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${LAKE_DB_USER}
            - POSTGRES_PASSWORD=${LAKE_DB_PASSWORD}
            - POSTGRES_DB=${LAKE_DB_NAME}
        volumes:
            - store_lake:/var/lib/postgresql
            - ../backup/migrate.load:/migrate.load
    db_mart:
        container_name: postgres
        image: postgres:latest
        ports:
            - "5433:5433"
        environment:
            - POSTGRES_USER=${MART_DB_USER}
            - POSTGRES_PASSWORD=${MART_DB_PASSWORD}
            - POSTGRES_DB=${MART_DB_NAME}
        volumes:
            - store_mart:/var/lib/postgresql
    app:
        build:
            context: "../"
            dockerfile: docker/Dockerfile
        restart: always
        depends_on:
            - db_mart
            - db
        container_name: aquila
        links:
            - db_mart
            - db
        environment:
            - LAKE_DB_NAME=${LAKE_DB_NAME}
            - LAKE_DB_USER=${LAKE_DB_USER}
            - LAKE_DB_PASSWORD=${LAKE_DB_PASSWORD}
            - LAKE_DB_HOST=${LAKE_DB_HOST}
            - LAKE_DB_PORT=${LAKE_DB_PORT}
            - MART_DB_NAME=${MART_DB_NAME}
            - MART_DB_USER=${MART_DB_USER}
            - MART_DB_PASSWORD=${MART_DB_PASSWORD}
            - MART_DB_HOST=${MART_DB_HOST}
            - MART_DB_PORT=${MART_DB_PORT}
            - LAKE_MSSQL_DB_NAME=${LAKE_MSSQL_DB_NAME}
            - LAKE_MSSQL_DB_USER=${LAKE_MSSQL_DB_USER}
            - LAKE_MSSQL_DB_PASSWORD=${LAKE_MSSQL_DB_PASSWORD}
            - LAKE_MSSQL_DB_HOST=${LAKE_MSSQL_DB_HOST}
        ports:
            - "8000:8000"
        volumes:
            - ../:/code
            - aquila_logs:/var/log
        command: python3 manage.py runserver 0.0.0.0:8000
